version: '3.8'

networks:
    api_network:

services:
    api_nginx:
        container_name: api_nginx
        image: nginx
        volumes:
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./:/var/www/
        ports:
            - '8080:80'
        depends_on:
            - api_app
        networks:
            - api_network

    api_app:
        container_name: api_app
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ._docker/conf.d/:/etc/nginx/conf.d/
            - ./:/var/www/
        depends_on:
            - api_db
        networks:
            - api_network

    api_db:
        container_name: api_db
        image: mysql:9.0.1
        restart: always
        volumes:
            - ./tmp/db/:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "{DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        ports:
            - '8101:3306'
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        networks:
            - api_network

    adminer:
        image: adminer
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: api_db
        ports:
            - '8086:8080'
        networks:
            - api_network
